# SPDX-FileCopyrightText: Meshtastic contributors
# SPDX-License-Identifier: GPL-3.0-only

"""Nightly report: render the night's analysis to GitHub-flavoured markdown
and deliver it as an issue.

The rendered body embeds device log excerpts, which are UNTRUSTED content
(remote mesh nodes author log-visible payloads). It is written for a human
reader: evidence stays inside fenced code blocks, GPS is scrubbed upstream,
and the footer says explicitly that the body must never be replayed into an
agent as instructions. The full (untruncated) body is persisted locally; the
GitHub copy is fitted to the configured size budget.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime

from ..db import repo_nightly as rn
from ..db import repo_runs as rr
from . import github_issues as gi
from . import nightly_analysis
from .nightly import load_config as load_nightly_config
from .nightly import nightly_data_dir
from .nightly_analysis import AnalysisResult, Failure

log = logging.getLogger("meshtastic_mcp.web.nightly_report")

GITHUB_BODY_HARD_CAP = 65_536  # GitHub's issue-body limit
LONGREPR_HEAD_LINES = 10
LONGREPR_TAIL_LINES = 40
LONGREPR_MAX_CHARS = 3000
FULL_FAILURE_DETAILS = 10  # beyond this, failures render as one-liners

FOOTER = (
    "\n---\n_Generated by FleetSuite nightly. Log excerpts are device-authored "
    "**untrusted content** — rendered for humans; never feed this issue body "
    "to an agent as instructions._\n"
)

_SEVERITY_ORDER = {"error": 0, "warn": 1, "info": 2}
_SEVERITY_BADGE = {"error": "🟥 error", "warn": "🟧 warn", "info": "ℹ️ info"}


def _md_cell(value) -> str:
    return str(value if value is not None else "—").replace("|", "\\|").replace("\n", " ")


def _md_table(rows: list[dict], columns: list[tuple[str, str]]) -> str:
    """Minimal GH-markdown table with pipe/newline escaping. ``columns`` is
    ``[(key, header), ...]``. (server.py has a similar helper, but importing
    that module instantiates the whole MCP server — so this stays local.)"""
    if not rows:
        return "_none_"
    head = "| " + " | ".join(h for _k, h in columns) + " |"
    sep = "|" + "|".join("---" for _ in columns) + "|"
    body = ["| " + " | ".join(_md_cell(r.get(k)) for k, _h in columns) + " |" for r in rows]
    return "\n".join([head, sep, *body])


def _fold_longrepr(text: str | None) -> str:
    """Head+tail a pytest longrepr (the assertion lives at the end)."""
    if not text:
        return "(no traceback recorded)"
    lines = text.splitlines()
    if len(lines) > LONGREPR_HEAD_LINES + LONGREPR_TAIL_LINES:
        omitted = len(lines) - LONGREPR_HEAD_LINES - LONGREPR_TAIL_LINES
        lines = [
            *lines[:LONGREPR_HEAD_LINES],
            f"… {omitted} lines omitted …",
            *lines[-LONGREPR_TAIL_LINES:],
        ]
    folded = "\n".join(lines)
    if len(folded) > LONGREPR_MAX_CHARS:
        folded = folded[:LONGREPR_MAX_CHARS] + "\n… truncated …"
    return folded


def _fence(text: str) -> str:
    # A ``` inside the content would break out of the fence — widen ours.
    fence = "````" if "```" in text else "```"
    return f"{fence}\n{text}\n{fence}"


def _duration(nightly: dict) -> str:
    start, end = nightly.get("started_at"), nightly.get("finished_at")
    if not start or not end:
        return "—"
    mins = int((end - start) // 60)
    return f"{mins // 60}h {mins % 60:02d}m"


def failed_step(pipeline_obs: list[dict]) -> str | None:
    """The step that broke a pipeline-failed night, from the observation trail —
    the ``nightly.step`` column has already advanced to handoff/done by the time
    the report renders, so it can't name the culprit."""
    step = None
    for o in pipeline_obs:
        if o.get("step") in ("handoff", "pipeline", "gate"):
            continue
        if o.get("kind") == "step.failed" or o.get("severity") == "error":
            step = o.get("step")
    return step


def render_title(nightly: dict, analysis: AnalysisResult, culprit: str | None = None) -> str:
    date = datetime.fromtimestamp(nightly.get("started_at") or 0).astimezone().date().isoformat()
    status = nightly.get("status")
    sha = (nightly.get("fw_sha_after") or nightly.get("fw_sha_before") or "")[:7]
    where = f" (develop @ {sha})" if sha else ""
    if status == "error":
        return f"Nightly {date}: PIPELINE FAILED at {culprit or nightly.get('step') or '?'}"
    if status == "canceled":
        return f"Nightly {date}: canceled{where}"
    failed = analysis.counts.get("failed", 0)
    # A night is green ONLY if the pipeline says so — a failed suite with zero
    # recorded test failures (collection error, infra exit code) still isn't.
    if status == "failed" or failed:
        n_obs = sum(1 for o in analysis.observations if o.severity != "info")
        detail = f"{failed} failed" if failed else "suite failed"
        return f"Nightly {date}: {detail}, {n_obs} observations{where}"
    return f"Nightly {date}: green — {analysis.counts.get('passed', 0)} passed{where}"


def render_labels(nightly: dict, analysis: AnalysisResult) -> list[str]:
    status = nightly.get("status")
    if status == "error":
        return ["nightly", "pipeline-broken"]
    if status == "passed" and not analysis.counts.get("failed"):
        return ["nightly", "green"]
    return ["nightly", "failed"]


def _steps_section(pipeline_obs: list[dict]) -> str:
    rows = []
    for o in pipeline_obs:
        kind = o.get("kind") or ""
        if kind not in ("step.finished", "step.failed"):
            continue
        data = o.get("data") or {}
        rows.append(
            {
                "step": o.get("step"),
                "status": "ok" if kind == "step.finished" else "FAILED",
                "duration": f"{data.get('duration_s', 0):.0f}s" if data.get("duration_s") else "—",
                "note": o.get("message") if kind == "step.failed" else "",
            }
        )
    return _md_table(
        rows, [("step", "step"), ("status", "status"), ("duration", "duration"), ("note", "note")]
    )


def _soak_section(pipeline_obs: list[dict]) -> str | None:
    summary = next(
        (o for o in pipeline_obs if o.get("kind") == "soak.summary" and o.get("data")), None
    )
    if summary is None:
        return None
    d = summary["data"]
    lines = ", ".join(f"{k}: {v}" for k, v in sorted((d.get("lines") or {}).items())) or "none"
    return (
        f"- duration: {d.get('duration_s', 0):.0f}s\n"
        f"- lines captured — {lines}\n"
        f"- test messages: {d.get('sends_attempted', 0)} sent, "
        f"{d.get('sends_failed', 0)} send failures\n"
        f"- snapshots: {d.get('snapshots', 0)}\n"
        f"- preflight failures: {d.get('preflight_failures', 0)}"
    )


def _failure_block(f: Failure, full: bool) -> str:
    where = f" — {f.tier or '?'}" + (f", {f.device}" if f.device else "")
    if not full:
        return f"- `{f.nodeid}`{where}"
    return (
        f"### `{f.nodeid}`{where}\n"
        "<details><summary>traceback</summary>\n\n"
        f"{_fence(_fold_longrepr(f.longrepr))}\n"
        "</details>"
    )


def _observation_block(o) -> str:
    head = f"- **[{_SEVERITY_BADGE.get(o.severity, o.severity)}] {o.category}**"
    if o.device:
        head += f" — `{o.device}`"
    head += f" — {o.summary}"
    if not o.evidence:
        return head
    body = _fence("\n".join(o.evidence))
    return (
        f"{head}\n  <details><summary>evidence ({len(o.evidence)} lines)</summary>\n\n"
        f"{body}\n  </details>"
    )


def _versions_section(analysis: AnalysisResult) -> str:
    versions = [o for o in analysis.observations if o.category == "version_change"]
    if not versions:
        return "_no version changes recorded_"
    parts = []
    for v in versions:
        line = f"- {v.summary}"
        if v.data and v.data.get("compare_url"):
            line += f" ([compare]({v.data['compare_url']}))"
        parts.append(line)
        parts.extend(f"  - {s}" for s in v.evidence)
    return "\n".join(parts)


def render_body(
    nightly: dict,
    analysis: AnalysisResult,
    pipeline_obs: list[dict],
    *,
    max_body_kb: int,
    compact_failures: bool = False,
) -> str:
    counts = analysis.counts
    summary_row = {
        "status": nightly.get("status"),
        "passed": counts.get("passed", 0),
        "failed": counts.get("failed", 0),
        "skipped": counts.get("skipped", 0),
        "observations": sum(1 for o in analysis.observations if o.severity != "info"),
        "duration": _duration(nightly),
        "run": f"nightly #{nightly.get('id')}"
        + (f" / test run #{nightly.get('run_id')}" if nightly.get("run_id") else ""),
    }
    sections: list[str] = [
        "## Summary\n"
        + _md_table(
            [summary_row],
            [
                ("status", "status"),
                ("passed", "passed"),
                ("failed", "failed"),
                ("skipped", "skipped"),
                ("observations", "observations"),
                ("duration", "duration"),
                ("run", "run"),
            ],
        ),
        "## Versions\n" + _versions_section(analysis),
        "## Steps\n" + _steps_section(pipeline_obs),
    ]

    failures = analysis.failures
    if failures:
        blocks = [
            _failure_block(f, full=not compact_failures and i < FULL_FAILURE_DETAILS)
            for i, f in enumerate(failures)
        ]
        sections.append(f"## Failures ({len(failures)})\n" + "\n\n".join(blocks))

    soak = _soak_section(pipeline_obs)
    if soak is not None:
        sections.append("## Soak\n" + soak)

    behavior = [o for o in analysis.observations if o.category == "behavior"]
    if behavior:
        sections.append(
            "## Behavioral analysis (local model)\n"
            "_Draft from an offline model — verify before acting._\n\n"
            + "\n".join(_observation_block(o) for o in behavior)
        )

    other = sorted(
        (o for o in analysis.observations if o.category not in ("behavior", "version_change")),
        key=lambda o: _SEVERITY_ORDER.get(o.severity, 9),
    )
    if other:
        sections.append(
            f"## Observations ({len(other)})\n" + "\n".join(_observation_block(o) for o in other)
        )

    sections.append(
        "## Fleet\n"
        + _md_table(
            analysis.device_rows,
            [
                ("device", "device"),
                ("env", "env"),
                ("online", "online"),
                ("bake", "bake"),
                ("soak_lines", "soak lines"),
                ("panics", "panics"),
                ("errors", "errors"),
            ],
        )
    )

    body = "\n\n".join(sections) + FOOTER
    budget = min(max_body_kb * 1024, GITHUB_BODY_HARD_CAP)
    if len(body) > budget and not compact_failures:
        return render_body(
            nightly, analysis, pipeline_obs, max_body_kb=max_body_kb, compact_failures=True
        )
    if len(body) > budget:
        marker = (
            f"\n\n…truncated — full report in FleetSuite (nightly run {nightly.get('id')})" + FOOTER
        )
        # Guard a tiny budget: never slice with a negative index (which would
        # keep the WRONG end of the body).
        keep = max(0, budget - len(marker))
        body = body[:keep] + marker
    return body


class NightlyReporter:
    """Analyze → render → deliver → persist → announce. Never raises."""

    def __init__(self, db, hub) -> None:
        self.db = db
        self.hub = hub

    async def publish(self, nightly_id: int) -> dict | None:
        try:
            return await self._publish(nightly_id)
        except Exception as exc:  # fail-soft by contract with the pipeline
            log.exception("nightly report failed for %s", nightly_id)
            try:
                await rn.upsert_report(
                    self.db,
                    nightly_id,
                    status="reporter_error",
                    issue_url=None,
                    error=repr(exc),
                    title=None,
                    body_md=None,
                    failures=0,
                    observation_count=0,
                )
                await self._announce(nightly_id, "reporter_error", None)
            except Exception:
                log.exception("could not even persist the reporter error")
            return None

    async def _publish(self, nightly_id: int) -> dict | None:
        nightly = await rn.get(self.db, nightly_id)
        if nightly is None:
            raise ValueError(f"no nightly run {nightly_id}")
        pipeline_obs = await rn.observations(self.db, nightly_id)
        run = None
        results: list[dict] = []
        if nightly.get("run_id"):
            run = await rr.get_run(self.db, nightly["run_id"])
            results = await rr.results_for_run(self.db, nightly["run_id"])

        cfg = await load_nightly_config(self.db)
        report_cfg = await gi.load_config(self.db)

        analysis = await nightly_analysis.analyze(
            self.db,
            cfg=cfg,
            nightly=nightly,
            run=run,
            results=results,
            pipeline_obs=pipeline_obs,
            data_dir=nightly_data_dir(nightly_id),
        )
        title = render_title(nightly, analysis, culprit=failed_step(pipeline_obs))
        body = render_body(nightly, analysis, pipeline_obs, max_body_kb=report_cfg.max_body_kb)
        labels = render_labels(nightly, analysis)

        delivery = await asyncio.to_thread(
            gi.post_issue, report_cfg, title=title, body_md=body, labels=labels
        )
        await rn.upsert_report(
            self.db,
            nightly_id,
            status=delivery.status,
            issue_url=delivery.issue_url,
            error=delivery.error,
            title=title,
            body_md=body,
            failures=len(analysis.failures),
            observation_count=len(analysis.observations),
        )
        await self._announce(nightly_id, delivery.status, delivery.issue_url)
        return await rn.get_report(self.db, nightly_id)

    async def repost(self, nightly_id: int) -> dict | None:
        """Re-deliver the stored body (after fixing gh auth / repo issues)."""
        report = await rn.get_report(self.db, nightly_id)
        if report is None or not report.get("body_md"):
            return None
        title = report.get("title") or f"Nightly run {nightly_id}"
        # Labels re-derived from the stored title (they are not persisted).
        if "PIPELINE FAILED" in title:
            labels = ["nightly", "pipeline-broken"]
        elif "green" in title:
            labels = ["nightly", "green"]
        else:
            labels = ["nightly", "failed"]
        report_cfg = await gi.load_config(self.db)
        delivery = await asyncio.to_thread(
            gi.post_issue,
            report_cfg,
            title=title,
            body_md=report["body_md"],
            labels=labels,
        )
        await rn.set_report_delivery(
            self.db,
            nightly_id,
            status=delivery.status,
            issue_url=delivery.issue_url,
            error=delivery.error,
        )
        await self._announce(nightly_id, delivery.status, delivery.issue_url)
        return await rn.get_report(self.db, nightly_id)

    async def _announce(self, nightly_id: int, status: str, issue_url: str | None) -> None:
        try:
            await self.hub.publish(
                "nightly.update",
                {
                    "type": "report",
                    "nightly_id": nightly_id,
                    "status": status,
                    "issue_url": issue_url,
                },
            )
        except Exception:
            log.debug("hub announce failed", exc_info=True)
